
CREATE SCHEMA VITRSA_SANDBOX;

CREATE SEQUENCE VITRSA_SANDBOX.VIT_RSA_GENERIC_SEQ
    START WITH 50002
    INCREMENT BY 1;

CREATE TABLE VITRSA_SANDBOX.DEMO_ACCOUNT_TYPE
(
        ACCOUNT_TYPE_ID BIGINT      NOT NULL,
        MNEMONIC        VARCHAR(100) NOT NULL UNIQUE,
        ACCOUNT_TYPE_NAME       VARCHAR(255) NOT NULL,
        CREATION_DATE       DATE    NOT NULL,
        PRIMARY KEY (ACCOUNT_TYPE_ID)
);

CREATE TABLE VITRSA_SANDBOX.ACCOUNT_TX
(
        TX_ID BIGINT      NOT NULL,
        ACCOUNT_TYPE_ID BIGINT        NOT NULL,
        MEMBER_ID BIGINT       NOT NULL,
        AMOUNT BIGINT       NOT NULL,
        TX_DATE     DATE    NOT NULL,
        PRIMARY KEY (TX_ID),
        CONSTRAINT FK_ACCOUNT_TYPE_IOL FOREIGN KEY (ACCOUNT_TYPE_ID) REFERENCES VITRSA_SANDBOX.DEMO_ACCOUNT_TYPE (ACCOUNT_TYPE_ID),

);

CREATE TABLE VITRSA_SANDBOX.ACCOUNT_TX.DETAILS(
        ACCOUNT_TX_DETAILS_ID BIGINT        NOT NULL,
        TX_ID BIGINT        NOT NULL,
        PARTNER_NAME            VARCHAR(255) NOT NULL,
        NUMBER_OF_ITEMS BIGINT      NOT NULL,
        PRIMARY KEY (ACCOUNT_TX_DETAILS_ID),
        CONSTRAINT FK_ACCOUNT_TX_ID FOREIGN KEY (TX_ID) REFERENCES DEMO_SCHEMA.ACCOUNT_TX (TX_ID)
)
